### ISSUE TITLE
Model schema & persistent storage interfaces

### ISSUE THREAD

**Issue by hexus** [darya/framework#11]
Find the best way for a `Record` to expose its schema. It really might not matter if this is a static property in the long run.

Extract all the static `load`, `save`, and `delete` methods to a generic MySQL repository that is instantiated with a connection. `Record` can then have a `sharedRepository` property instead of a `sharedConnection`. These static methods can then simply use this repository, or maybe even a `__callStatic` magic method implementation would suffice.

This allows a `Model` instance to be passed to repositories for persistence at the same time as retaining the convenience methods on `Record` subclasses, without said methods containing messy conditions and hard-coded SQL.

**Comment by hexusio** [comment]
So far in the `database` branch this has been implemented using the new `Darya\Storage` interfaces. Active record classes have been moved to the `Darya\ORM` namespace.

**Comment by hexus** [comment]
This has basically been implemented a while ago, on eager loading now.
