### ISSUE TITLE
Improve Model & Controller API

### ISSUE THREAD

**Issue by hexus** [darya/framework#9]
Remove redundant methods. Implement attributes specifications.

Possibly make it easier to generate the current controller's URL:

```php
return $this->request->route->url();
```

**Comment by hexusio** [comment]
Really this is related to #11

**Comment by hexus** [comment]
While base controllers aren't necessary with the power of the service container, it's still convenient to have for methods like this.

**Comment by hexus** [comment]
This is sorted now. Model has had quite an overhaul and the controller helper method has been implemented.
